#!/usr/bin/env python
# coding: utf-8

# # Processing UV-Vis spectra obtained from the Beckman Coulter DU-640 spectrophotometer
# 
# 0. Imports

# In[2]:


import os
from .util import isFloat


# 1. The following is an example of an absorption spectrum text file obtained form the Beckman Coulter DU-640 spectrophotometer.

# User ID: DU600
# 
# Method ID: A:\DEFAULT
# 
# Date: 07/25/00
# 
# Time: 12:02
# 
#  200.0   0.25060
# 
#   201.0   0.25706
# 
#   202.0   0.25690
# 
#   203.0   0.26161
# 
#   204.0   0.26775
# 
#   205.0   0.27486
# 
#   206.0   0.27792
# 
#   207.0   0.28106

# In[3]:


def readSpectrumFromFile(path_to_file):
    '''Extracts the absorption spectrum from the text file generated by a Beckman Coulter DU-640 spectrophotometer

    Parameters
    ----------
    path_to_file : string
        Path used to locate the spectrum text file.

    Returns
    -------
    array of tuples
       absorption spectrum
       The first element of each tuple is the wavelength in nanometers. 
       The second element is the absorbance measurement in absorbance units.
    '''
    with open(path_to_file) as f:
        spectrum = [
            tuple(map(float, line.strip().split())) 
            for line in f.readlines()
                if (line.strip() and all([isFloat(word) for word in line.strip().split()]))
        ]
    return spectrum

